baseURL = 'https://ansel.photos/'
defaultContentLanguage = 'en'
copyright = '© Copyright 2022 – Aurélien Pierre'
title = 'Ansel'
theme = 'ansel'
enableGitInfo = true
defaultContentLanguageInSubdir = true
canonifyURLs = true

[author]
  name = 'Aurélien Pierre'
  GitHubUser = 'aurelienpierre'
  url = "https://aurelienpierre.com"

[menu]
  [[menu.main]]
    identifier = "workflows"
    name = "Workflows"
    pre = "fas fa-paint-roller"
    url = "/workflows/"
    weight = 1

  [[menu.main]]
    identifier = "news"
    name = "News"
    pre = "fas fa-newspaper"
    url = "/news/"
    weight = 2

  [[menu.main]]
    identifier = "support"
    name = "Support"
    pre = "fas fa-hands-helping"
    url = "/support/"
    weight = 3

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    pre = "fas fa-book"
    url = "/doc/"
    weight = 3

[languages]
  [languages.en]
    title = 'Ansel'
    languagename = "English"
    weight = 1
  [languages.fr]
    title = 'Ansel'
    languagename = "Français"
    weight = 2

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.goldmark.renderer]
    unsafe = true

[module]
  replacements = '/ -> /doc/'
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/aurelien-pierre/ansel-doc"

    [[module.imports.mounts]]
      source = 'content/'
      target = 'content/doc/'
      lang= "en"

    [[module.imports.mounts]]
      source = 'content/'
      target = 'content/doc/'
      lang= "fr"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[taxonomies]
  tag = "tags"
